; ==================================================================================================
; Projeto   : Robô Cartesiano
; Arquivo   : robo_input.ini
; Descrição : Arquivo de configuração da execução do robô.
; Autor     : Charles Cesar Magno de Freitas
; Licença   : MIT
; ==================================================================================================

[PLANO]
X_MINIMO = -10      ; Coordenada mínima do eixo X.
X_MAXIMO = 10       ; Coordenada máxima do eixo X.
Y_MINIMO = -8       ; Coordenada mínima do eixo Y.
Y_MAXIMO = 8        ; Coordenada máxima do eixo Y.


[ROBO]

POSICAO_INICIAL_X = 0   ; Coordenada inicial do robô no eixo X.
POSICAO_INICIAL_Y = 0   ; Coordenada inicial do robô no eixo Y.
PASSO = 1               ; Valor do deslocamento aplicado em cada movimento.
                        ; Deve ser obrigatoriamente maior que zero.

[MOVIMENTOS]
; Sequência de comandos.
; São aceitos caracteres maiúsculos e minúsculos.
;
; Comandos válidos:
; N = Norte             S = Sul
; L = Leste             O = Oeste
; E = Nordeste          Q = Noroeste
; C = Sudeste           Z = Sudoeste
;
; Todos os demais caracteres serão ignorados.
SEQUENCIA = NnLsOneSOXYZ123abcNNEESSOONLSESONONELSO